apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-demo-1
  namespace: vm-demo
  labels:
    app: db
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-8-silver-hedgehog-67-volume-1
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    kind: virtualmachineclusterinstancetype
    name: u1.small
  preference:
    kind: virtualmachineclusterpreference
    name: rhel.8
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: ssh-bastion
      architecture: amd64
      domain:
        devices:
          autoattachPodInterface: false
          interfaces:
            - macAddress: '02:78:30:00:00:00'
              masquerade: {}
              name: default
        machine:
          type: pc-q35-rhel9.4.0
        resources: {}
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: rhel-8-silver-hedgehog-67-volume-1
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: 1qof-t2mc-kf23
              user: rhel
              runcmd: []
          name: cloudinitdisk

