apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-demo-2
  namespace: vm-demo
  labels:
    app: db
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhel-8-silver-hedgehog-67-volume-2
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        devices:
          autoattachPodInterface: true
        machine:
          type: pc-q35-rhel9.4.0
        resources: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: rhel-8-silver-hedgehog-67-volume-2
          name: rootdisk
        - dataVolume:
            hotpluggable: true
            name: dv-vm-demo-1-crimson-anaconda-92
          name: disk-scarlet-boar-22
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: 1qof-t2mc-kf23
              user: rhel
              runcmd: []
          name: cloudinitdisk
